#include<iostream>
using namespace std;
main(){
int no1,no2,no3,no4,no5,no6,no7,no8,no9,no10,no11,no12,no13,no14,no15,sum,multiply,subtract,total;
cout<<"enter 1st number:";
cin>>no1;
cout<<"enter 2nd number:";
cin>>no2;
cout<<"enter 3rd number:";
cin>>no3;
cout<<"enter 4th number:";
cin>>no4;
cout<<"enter 5th number:";
cin>>no5;
cout<<"enter 6th number:";
cin>>no6;
cout<<"enter 7th number:";
cin>>no7;
cout<<"enter 8th number:";
cin>>no8;
cout<<"enter 9th number:";
cin>>no9;
cout<<"enter 10th number:";
cin>>no10;
cout<<"enter 11th number:";
cin>>no11;
cout<<"enter 12th number:";
cin>>no12;
cout<<"enter 13th number:";
cin>>no13;
cout<<"enter 14th number:";
cin>>no14;
cout<<"enter 15th number:";
cin>>no15; 
sum=no1+no2+no3+no4+no5;
multiply=no6*no7*no8*no9*no10;
subtract=no11-no12-no13-no14-no15;
total=(sum+multiply)-subtract;
cout<<"total="<<total;
}